spring:
  profiles:
    active: ${APP_PROFILE:dev}

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
        add-mappings: false
