spring: 
  datasource: 
    url: jdbc:postgresql://localhost:5432/algafood?serverTimezone=UTC
    username: postgres
    password: 1234
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration,classpath:db/testdata
